# Generated by Django 5.2.6 on 2025-09-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("FRUITS", "Fresh Fruits"),
                            ("VEGGIES", "Fresh Vegetables"),
                            ("DAIRY", "Dairy & Eggs"),
                            ("MEAT", "Meat & Seafood"),
                            ("BAKERY", "Bakery & Snacks"),
                            ("BEV", "Beverages"),
                            ("ESSENTIALS", "Daily Essentials"),
                            ("FROZEN", "Frozen Foods"),
                            ("HOUSE", "Household Essentials"),
                            ("CARE", "Personal Care & Health"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "offer_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="use url for now later use imgur or cloudinary api...<dev>"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity",
                        to="user.item",
                    ),
                ),
            ],
        ),
    ]
